version: 1
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.NPM_TOKEN}}

updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    registries: '*'
    target-branch: 'dev'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: 'daily'
    reviewers:
      - 'monaco-digital/Developers'
